version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-product
    environment:
      POSTGRES_DB: product_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  product-service:
    build: .
    container_name: product-service
    ports:
      - "8081:8080"
    depends_on:
      - postgres